### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [mossyfred/prj-rev-bwfs-dasmoto#5]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques here and your css was very efficient. Take a look at the issues I created as they will help you tweak a few things for best practice. Here is a good article with some tips: 
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by mossyfred** [comment]
Thanks for the review Ryan. The link and comments you included are helpful, I had seen the link earlier through Slack and now wish I'd used it!
